//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCNT
    {
        public string USERID { get; set; }
        public string UNAME { get; set; }
        public string ADD1 { get; set; }
        public string ADD2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string EMAIL_ADD { get; set; }
        public Nullable<System.DateTime> ANNUALPYMNTEXPIRED { get; set; }
        public string CC_HOLDER { get; set; }
        public string CC_NM { get; set; }
        public string MACADDRESS { get; set; }
        public string REFERREDBY { get; set; }
        public Nullable<System.DateTime> REGTIME { get; set; }
        public Nullable<int> LASTPAY100 { get; set; }
        public string PAYPERIOD { get; set; }
        public Nullable<System.DateTime> LASTPAYTIME { get; set; }
        public string CC_TYPE { get; set; }
        public string CC_FOUR { get; set; }
    }
}
