//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public string FACID { get; set; }
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CAP1 { get; set; }
        public Nullable<int> CAP2 { get; set; }
        public Nullable<int> CAP3 { get; set; }
        public Nullable<int> CAP4 { get; set; }
        public Nullable<int> CAP5 { get; set; }
        public Nullable<int> CAP6 { get; set; }
        public Nullable<int> CAP7 { get; set; }
        public Nullable<int> CAP8 { get; set; }
        public Nullable<int> CAP9 { get; set; }
        public Nullable<int> CAP10 { get; set; }
        public Nullable<int> CAP11 { get; set; }
        public Nullable<int> CAP12 { get; set; }
        public Nullable<int> CAP13 { get; set; }
        public Nullable<int> CAP14 { get; set; }
        public Nullable<int> CAP15 { get; set; }
        public Nullable<int> CAP16 { get; set; }
        public Nullable<int> CAP17 { get; set; }
        public Nullable<int> CAP18 { get; set; }
        public Nullable<int> PAR1 { get; set; }
        public Nullable<int> PAR2 { get; set; }
        public Nullable<int> PAR3 { get; set; }
        public Nullable<int> PAR4 { get; set; }
        public Nullable<int> PAR5 { get; set; }
        public Nullable<int> PAR6 { get; set; }
        public Nullable<int> PAR7 { get; set; }
        public Nullable<int> PAR8 { get; set; }
        public Nullable<int> PAR9 { get; set; }
        public Nullable<int> PAR10 { get; set; }
        public Nullable<int> PAR11 { get; set; }
        public Nullable<int> PAR12 { get; set; }
        public Nullable<int> PAR13 { get; set; }
        public Nullable<int> PAR14 { get; set; }
        public Nullable<int> PAR15 { get; set; }
        public Nullable<int> PAR16 { get; set; }
        public Nullable<int> PAR17 { get; set; }
        public Nullable<int> PAR18 { get; set; }
        public Nullable<int> YDG1 { get; set; }
        public Nullable<int> YDG2 { get; set; }
        public Nullable<int> YDG3 { get; set; }
        public Nullable<int> YDG4 { get; set; }
        public Nullable<int> YDG5 { get; set; }
        public Nullable<int> YDG6 { get; set; }
        public Nullable<int> YDG7 { get; set; }
        public Nullable<int> YDG8 { get; set; }
        public Nullable<int> YDG9 { get; set; }
        public Nullable<int> YDG10 { get; set; }
        public Nullable<int> YDG11 { get; set; }
        public Nullable<int> YDG12 { get; set; }
        public Nullable<int> YDG13 { get; set; }
        public Nullable<int> YDG14 { get; set; }
        public Nullable<int> YDG15 { get; set; }
        public Nullable<int> YDG16 { get; set; }
        public Nullable<int> YDG17 { get; set; }
        public Nullable<int> YDG18 { get; set; }
        public Nullable<double> RATING { get; set; }
        public Nullable<int> SLOPE { get; set; }
        public Nullable<int> DELETED { get; set; }
        public Nullable<int> GREENSIZE { get; set; }
        public Nullable<int> WD1 { get; set; }
        public Nullable<int> WD2 { get; set; }
        public Nullable<int> WD3 { get; set; }
        public Nullable<int> WD4 { get; set; }
        public Nullable<int> WD5 { get; set; }
        public Nullable<int> WD6 { get; set; }
        public Nullable<int> WD7 { get; set; }
        public Nullable<int> WD8 { get; set; }
        public Nullable<int> WD9 { get; set; }
        public Nullable<int> WD10 { get; set; }
        public Nullable<int> WD11 { get; set; }
        public Nullable<int> WD12 { get; set; }
        public Nullable<int> WD13 { get; set; }
        public Nullable<int> WD14 { get; set; }
        public Nullable<int> WD15 { get; set; }
        public Nullable<int> WD16 { get; set; }
        public Nullable<int> WD17 { get; set; }
        public Nullable<int> WD18 { get; set; }
        public Nullable<int> DP1 { get; set; }
        public Nullable<int> DP2 { get; set; }
        public Nullable<int> DP3 { get; set; }
        public Nullable<int> DP4 { get; set; }
        public Nullable<int> DP5 { get; set; }
        public Nullable<int> DP6 { get; set; }
        public Nullable<int> DP7 { get; set; }
        public Nullable<int> DP8 { get; set; }
        public Nullable<int> DP9 { get; set; }
        public Nullable<int> DP10 { get; set; }
        public Nullable<int> DP11 { get; set; }
        public Nullable<int> DP12 { get; set; }
        public Nullable<int> DP13 { get; set; }
        public Nullable<int> DP14 { get; set; }
        public Nullable<int> DP15 { get; set; }
        public Nullable<int> DP16 { get; set; }
        public Nullable<int> DP17 { get; set; }
        public Nullable<int> DP18 { get; set; }
        public Nullable<int> LR1 { get; set; }
        public Nullable<int> LR2 { get; set; }
        public Nullable<int> LR3 { get; set; }
        public Nullable<int> LR4 { get; set; }
        public Nullable<int> LR5 { get; set; }
        public Nullable<int> LR6 { get; set; }
        public Nullable<int> LR7 { get; set; }
        public Nullable<int> LR8 { get; set; }
        public Nullable<int> LR9 { get; set; }
        public Nullable<int> LR10 { get; set; }
        public Nullable<int> LR11 { get; set; }
        public Nullable<int> LR12 { get; set; }
        public Nullable<int> LR13 { get; set; }
        public Nullable<int> LR14 { get; set; }
        public Nullable<int> LR15 { get; set; }
        public Nullable<int> LR16 { get; set; }
        public Nullable<int> LR17 { get; set; }
        public Nullable<int> LR18 { get; set; }
        public Nullable<int> FB1 { get; set; }
        public Nullable<int> FB2 { get; set; }
        public Nullable<int> FB3 { get; set; }
        public Nullable<int> FB4 { get; set; }
        public Nullable<int> FB5 { get; set; }
        public Nullable<int> FB6 { get; set; }
        public Nullable<int> FB7 { get; set; }
        public Nullable<int> FB8 { get; set; }
        public Nullable<int> FB9 { get; set; }
        public Nullable<int> FB10 { get; set; }
        public Nullable<int> FB11 { get; set; }
        public Nullable<int> FB12 { get; set; }
        public Nullable<int> FB13 { get; set; }
        public Nullable<int> FB14 { get; set; }
        public Nullable<int> FB15 { get; set; }
        public Nullable<int> FB16 { get; set; }
        public Nullable<int> FB17 { get; set; }
        public Nullable<int> FB18 { get; set; }
        public Nullable<int> YARDAGE { get; set; }
        public Nullable<int> TEECOLOR { get; set; }
    }
}
