//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRY
    {
        public int PLYERID { get; set; }
        public Nullable<int> H_1 { get; set; }
        public Nullable<int> H_2 { get; set; }
        public Nullable<int> H_3 { get; set; }
        public Nullable<int> H_4 { get; set; }
        public Nullable<int> H_5 { get; set; }
        public Nullable<int> H_6 { get; set; }
        public Nullable<int> H_7 { get; set; }
        public Nullable<int> H_8 { get; set; }
        public Nullable<int> H_9 { get; set; }
        public Nullable<int> H_10 { get; set; }
        public Nullable<int> H_11 { get; set; }
        public Nullable<int> H_12 { get; set; }
        public Nullable<int> H_13 { get; set; }
        public Nullable<int> H_14 { get; set; }
        public Nullable<int> H_15 { get; set; }
        public Nullable<int> H_16 { get; set; }
        public Nullable<int> H_17 { get; set; }
        public Nullable<int> H_18 { get; set; }
        public Nullable<int> H_19 { get; set; }
        public Nullable<int> FRONT { get; set; }
        public Nullable<int> BACK { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> ADJ_SCORE { get; set; }
    }
}
