//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public string FACID { get; set; }
        public System.DateTime PLYFLD { get; set; }
        public int PLYFLDNO { get; set; }
        public int TOURN_NO { get; set; }
        public Nullable<int> PLYERS_PER_TM { get; set; }
        public Nullable<int> NO_ROUNDS { get; set; }
        public Nullable<int> START_ROUND { get; set; }
        public Nullable<int> R1_FORMAT { get; set; }
        public Nullable<int> R2_FORMAT { get; set; }
        public Nullable<int> R3_FORMAT { get; set; }
        public Nullable<int> R4_FORMAT { get; set; }
        public Nullable<int> R5_FORMAT { get; set; }
        public Nullable<int> R1_COURSE { get; set; }
        public Nullable<int> R2_COURSE { get; set; }
        public Nullable<int> R3_COURSE { get; set; }
        public Nullable<int> R4_COURSE { get; set; }
        public Nullable<int> R5_COURSE { get; set; }
        public Nullable<int> SKINS { get; set; }
        public Nullable<int> NETSKINS { get; set; }
        public Nullable<int> HDCP_PCT { get; set; }
        public Nullable<int> IND_NET { get; set; }
        public Nullable<int> BLIND { get; set; }
        public Nullable<int> IND_GRS { get; set; }
        public Nullable<int> HDCP_TYP { get; set; }
        public string GM_NAME { get; set; }
        public string EV_NAME { get; set; }
        public Nullable<int> TM_SKINS { get; set; }
        public Nullable<int> LEAGUE { get; set; }
        public Nullable<int> X1_COURSE { get; set; }
        public Nullable<int> X2_COURSE { get; set; }
        public Nullable<int> X3_COURSE { get; set; }
        public Nullable<int> X4_COURSE { get; set; }
        public Nullable<int> X5_COURSE { get; set; }
        public Nullable<int> Y1_COURSE { get; set; }
        public Nullable<int> Y2_COURSE { get; set; }
        public Nullable<int> Y3_COURSE { get; set; }
        public Nullable<int> Y4_COURSE { get; set; }
        public Nullable<int> Y5_COURSE { get; set; }
        public Nullable<int> Z1_COURSE { get; set; }
        public Nullable<int> Z2_COURSE { get; set; }
        public Nullable<int> Z3_COURSE { get; set; }
        public Nullable<int> Z4_COURSE { get; set; }
        public Nullable<int> Z5_COURSE { get; set; }
        public Nullable<int> NINER { get; set; }
        public Nullable<int> F_OR_B1 { get; set; }
        public Nullable<int> F_OR_B2 { get; set; }
        public Nullable<int> F_OR_B3 { get; set; }
        public Nullable<int> F_OR_B4 { get; set; }
        public Nullable<int> F_OR_B5 { get; set; }
        public Nullable<int> MULT_COURSE { get; set; }
        public Nullable<int> RND_ROBIN { get; set; }
        public Nullable<int> SENT_UP { get; set; }
        public Nullable<int> QUOTABASE { get; set; }
        public Nullable<int> TMCAP_PCENT { get; set; }
        public Nullable<int> NOTE_WALKERS { get; set; }
        public Nullable<int> TR_OR_RND { get; set; }
        public Nullable<int> FLIGHTS { get; set; }
        public Nullable<int> RAT_ADJ { get; set; }
        public Nullable<int> SKIN_SPAN_TEE { get; set; }
        public Nullable<int> R6_FORMAT { get; set; }
        public Nullable<int> R6_COURSE { get; set; }
        public Nullable<int> X6_COURSE { get; set; }
        public Nullable<int> Y6_COURSE { get; set; }
        public Nullable<int> Z6_COURSE { get; set; }
        public Nullable<int> F_OR_B6 { get; set; }
        public Nullable<int> JUNK { get; set; }
        public Nullable<int> FBNINES { get; set; }
        public Nullable<int> TRUNKDOLL { get; set; }
        public Nullable<int> ROUNDDOLL { get; set; }
        public Nullable<int> SPONSOR { get; set; }
        public Nullable<int> RP_RESULTS { get; set; }
        public Nullable<int> TM_JUNK { get; set; }
        public Nullable<int> POST_SCORES { get; set; }
        public Nullable<int> LEAGRND { get; set; }
        public Nullable<int> LEAGTEEBOX { get; set; }
        public Nullable<int> HDCP_PCT_W { get; set; }
        public Nullable<int> AVG_HDCP { get; set; }
        public Nullable<int> CAPOFFLOW { get; set; }
    }
}
