//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACILITY
    {
        public string FACID { get; set; }
        public int FACILID { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string ZIP { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public Nullable<System.DateTime> ANNUALPYMNTTIME { get; set; }
        public string CC_HOLDER { get; set; }
        public string CC_TYPE { get; set; }
        public string CC_NO { get; set; }
        public byte[] LOGO { get; set; }
        public string BLIP1 { get; set; }
        public string BLIP2 { get; set; }
    }
}
