//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMAT
    {
        public string FACID { get; set; }
        public System.DateTime PLYFLD { get; set; }
        public int PLYFLDNO { get; set; }
        public int TOURN_NO { get; set; }
        public int RNDNO { get; set; }
        public Nullable<int> HOLE1 { get; set; }
        public Nullable<int> HOLE2 { get; set; }
        public Nullable<int> HOLE3 { get; set; }
        public Nullable<int> HOLE4 { get; set; }
        public Nullable<int> HOLE5 { get; set; }
        public Nullable<int> HOLE6 { get; set; }
        public Nullable<int> HOLE7 { get; set; }
        public Nullable<int> HOLE8 { get; set; }
        public Nullable<int> HOLE9 { get; set; }
        public Nullable<int> HOLE10 { get; set; }
        public Nullable<int> HOLE11 { get; set; }
        public Nullable<int> HOLE12 { get; set; }
        public Nullable<int> HOLE13 { get; set; }
        public Nullable<int> HOLE14 { get; set; }
        public Nullable<int> HOLE15 { get; set; }
        public Nullable<int> HOLE16 { get; set; }
        public Nullable<int> HOLE17 { get; set; }
        public Nullable<int> HOLE18 { get; set; }
    }
}
