//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDCP
    {
        public string FACID { get; set; }
        public int PLYERID { get; set; }
        public System.DateTime PLYFLD { get; set; }
        public int PLYFLDNO { get; set; }
        public int RNDNO { get; set; }
        public int LEAGUE { get; set; }
        public Nullable<int> GRS_SCORE { get; set; }
        public Nullable<int> ADJ_SCORE { get; set; }
        public string CRS_NAME { get; set; }
        public Nullable<double> CRS_RATING { get; set; }
        public Nullable<int> CRS_SLOPE { get; set; }
        public Nullable<double> DIFFERENTIAL { get; set; }
        public Nullable<int> HIDEIT { get; set; }
    }
}
