//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAGUE
    {
        public string FACID { get; set; }
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> MFORMAT { get; set; }
        public Nullable<int> LASTRND { get; set; }
        public Nullable<int> PPT { get; set; }
        public Nullable<int> DIVS { get; set; }
        public Nullable<int> TPD { get; set; }
        public Nullable<int> KEEP_LAST { get; set; }
        public Nullable<int> HI_THROW { get; set; }
        public Nullable<int> LO_THROW { get; set; }
        public Nullable<int> RNDS { get; set; }
        public Nullable<int> R1 { get; set; }
        public Nullable<int> R2 { get; set; }
        public Nullable<int> R3 { get; set; }
        public Nullable<int> R4 { get; set; }
        public Nullable<int> R5 { get; set; }
        public Nullable<int> R6 { get; set; }
        public Nullable<int> R7 { get; set; }
        public Nullable<int> R8 { get; set; }
        public Nullable<int> R9 { get; set; }
        public Nullable<int> R10 { get; set; }
        public Nullable<int> R11 { get; set; }
        public Nullable<int> R12 { get; set; }
        public Nullable<int> R13 { get; set; }
        public Nullable<int> R14 { get; set; }
        public Nullable<int> R15 { get; set; }
        public Nullable<int> R16 { get; set; }
        public Nullable<int> R17 { get; set; }
        public Nullable<int> R18 { get; set; }
        public Nullable<int> R19 { get; set; }
        public Nullable<int> R20 { get; set; }
        public Nullable<int> R21 { get; set; }
        public Nullable<int> R22 { get; set; }
        public Nullable<int> R23 { get; set; }
        public Nullable<int> R24 { get; set; }
        public Nullable<int> COURSEID { get; set; }
        public Nullable<int> NINEHOLE { get; set; }
        public Nullable<int> FORMAT { get; set; }
        public Nullable<int> POINTS { get; set; }
        public Nullable<int> EXTRAS { get; set; }
        public Nullable<int> MEDAL { get; set; }
        public Nullable<int> POINTFMT { get; set; }
        public Nullable<int> DIVISIONS { get; set; }
        public Nullable<int> NUMTEAMS { get; set; }
        public Nullable<int> ABCPOINTS { get; set; }
        public Nullable<int> ABCEXTRAS { get; set; }
        public Nullable<int> ABCNET { get; set; }
        public Nullable<int> ABCOFFLOW { get; set; }
    }
}
