//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAGPARAM
    {
        public string FACID { get; set; }
        public int ID { get; set; }
        public int ROUND { get; set; }
        public Nullable<int> POINTS { get; set; }
        public Nullable<int> EXTRAS { get; set; }
        public Nullable<int> MEDAL { get; set; }
        public Nullable<int> ABCPOINTS { get; set; }
        public Nullable<int> ABCEXTRAS { get; set; }
        public Nullable<int> ABCNET { get; set; }
        public Nullable<int> ABCOFFLOW { get; set; }
    }
}
