//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGSCORE
    {
        public string FACID { get; set; }
        public int LEAGUE { get; set; }
        public int RNDNO { get; set; }
        public int PLYERID { get; set; }
        public int NET { get; set; }
        public Nullable<int> T0_CP { get; set; }
        public Nullable<int> T0_TM { get; set; }
        public string ZNAME { get; set; }
        public Nullable<int> H_1 { get; set; }
        public Nullable<int> H_2 { get; set; }
        public Nullable<int> H_3 { get; set; }
        public Nullable<int> H_4 { get; set; }
        public Nullable<int> H_5 { get; set; }
        public Nullable<int> H_6 { get; set; }
        public Nullable<int> H_7 { get; set; }
        public Nullable<int> H_8 { get; set; }
        public Nullable<int> H_9 { get; set; }
        public Nullable<int> H_10 { get; set; }
        public Nullable<int> H_11 { get; set; }
        public Nullable<int> H_12 { get; set; }
        public Nullable<int> H_13 { get; set; }
        public Nullable<int> H_14 { get; set; }
        public Nullable<int> H_15 { get; set; }
        public Nullable<int> H_16 { get; set; }
        public Nullable<int> H_17 { get; set; }
        public Nullable<int> H_18 { get; set; }
        public Nullable<int> H_19 { get; set; }
        public Nullable<int> H_20 { get; set; }
        public Nullable<int> H_21 { get; set; }
        public Nullable<int> H_22 { get; set; }
        public Nullable<int> H_23 { get; set; }
        public Nullable<int> H_24 { get; set; }
        public Nullable<int> C_IND { get; set; }
        public Nullable<int> C_TM { get; set; }
        public Nullable<int> TEEORDER { get; set; }
        public Nullable<int> ORGORDER { get; set; }
        public Nullable<int> ORD1 { get; set; }
        public Nullable<int> ORD2 { get; set; }
        public Nullable<int> ORD3 { get; set; }
        public Nullable<int> ORD4 { get; set; }
        public Nullable<int> ORD5 { get; set; }
        public Nullable<int> ORD6 { get; set; }
        public Nullable<int> ORD7 { get; set; }
        public Nullable<int> ORD8 { get; set; }
        public Nullable<int> ORD9 { get; set; }
        public Nullable<int> ORD10 { get; set; }
        public Nullable<int> ORD11 { get; set; }
        public Nullable<int> ORD12 { get; set; }
        public Nullable<int> ORD13 { get; set; }
        public Nullable<int> ORD14 { get; set; }
        public Nullable<int> ORD15 { get; set; }
        public Nullable<int> ORD16 { get; set; }
        public Nullable<int> ORD17 { get; set; }
        public Nullable<int> ORD18 { get; set; }
        public Nullable<int> ORD19 { get; set; }
        public Nullable<int> ORD20 { get; set; }
        public Nullable<int> ORD21 { get; set; }
        public Nullable<int> ORD22 { get; set; }
        public Nullable<int> ORD23 { get; set; }
        public Nullable<int> ORD24 { get; set; }
    }
}
