//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERSHIP
    {
        public string FACID { get; set; }
        public int PID { get; set; }
        public string MAINADMIN { get; set; }
        public string COADMIN { get; set; }
    }
}
