//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TGLFEntities : DbContext
    {
        public TGLFEntities()
            : base("name=TGLFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCNT> ACCNTs { get; set; }
        public virtual DbSet<CARD> CARDs { get; set; }
        public virtual DbSet<COURSE> COURSEs { get; set; }
        public virtual DbSet<ENTRY> ENTRies { get; set; }
        public virtual DbSet<EVENT> EVENTs { get; set; }
        public virtual DbSet<FACILITY> FACILITies { get; set; }
        public virtual DbSet<FLIGHT> FLIGHTS { get; set; }
        public virtual DbSet<FORMAT> FORMATs { get; set; }
        public virtual DbSet<HDCP> HDCPs { get; set; }
        public virtual DbSet<LEAGPARAM> LEAGPARAMS { get; set; }
        public virtual DbSet<LEAGUE> LEAGUEs { get; set; }
        public virtual DbSet<LGSCORE> LGSCOREs { get; set; }
        public virtual DbSet<MEMBERSHIP> MEMBERSHIPs { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTS { get; set; }
        public virtual DbSet<PLAYER> PLAYERS { get; set; }
        public virtual DbSet<REGISTRY> REGISTRies { get; set; }
        public virtual DbSet<REMOVED> REMOVEDs { get; set; }
        public virtual DbSet<RESULT> RESULTS { get; set; }
        public virtual DbSet<SCORE> SCORES { get; set; }
        public virtual DbSet<TEETIME> TEETIMEs { get; set; }
    }
}
