//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public string FACID { get; set; }
        public System.DateTime PLYFLD { get; set; }
        public int PLYFLDNO { get; set; }
        public Nullable<int> PYMNT_NO { get; set; }
        public Nullable<System.DateTime> PYMNT_TIME { get; set; }
        public Nullable<int> AMT_PAID_100 { get; set; }
        public Nullable<int> NO_ROUNDS { get; set; }
        public Nullable<int> RND_ROBIN { get; set; }
        public string USERID { get; set; }
        public Nullable<int> NO_SEC_EVENTS { get; set; }
        public Nullable<double> AMT_PAID { get; set; }
        public string CC_TYPE { get; set; }
        public string CC_LAST_4 { get; set; }
        public string CC_NO { get; set; }
        public string EV_NAME { get; set; }
        public Nullable<int> NO_WEEKS { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
    }
}
