//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYER
    {
        public string MEMBER { get; set; }
        public int ID { get; set; }
        public Nullable<double> HDCP { get; set; }
        public string GENDER { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string PNAME { get; set; }
        public string USGATAG { get; set; }
        public Nullable<int> DELETED { get; set; }
        public Nullable<int> FEMALE { get; set; }
        public string HANDLE { get; set; }
        public string EMAIL { get; set; }
    }
}
