//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRY
    {
        public string FACID { get; set; }
        public int FACILID { get; set; }
        public Nullable<int> EVENTIDX { get; set; }
        public Nullable<int> GAMEIDX { get; set; }
        public Nullable<int> LEAGIDX { get; set; }
        public Nullable<int> BASEPAY { get; set; }
        public Nullable<int> CARDTYPE { get; set; }
        public Nullable<int> DISPROUND { get; set; }
        public Nullable<int> DISPBLOWS { get; set; }
        public Nullable<int> TEAMHDCP { get; set; }
        public Nullable<int> BOARDLINES { get; set; }
        public string SCORED1 { get; set; }
        public string SCORED2 { get; set; }
        public string SCORED3 { get; set; }
        public string SCORED4 { get; set; }
        public string EXPIRETEXT { get; set; }
        public Nullable<int> LMARGIN { get; set; }
        public Nullable<int> TMARGIN { get; set; }
        public Nullable<int> SBLABELS { get; set; }
        public Nullable<int> BGCOLOR { get; set; }
        public Nullable<int> BSIZE1 { get; set; }
        public Nullable<int> BSIZE2 { get; set; }
        public Nullable<int> BSIZE3 { get; set; }
        public Nullable<int> BSIZE4 { get; set; }
        public Nullable<int> BSIZE5 { get; set; }
        public Nullable<int> BORIENT1 { get; set; }
        public Nullable<int> BORIENT2 { get; set; }
        public Nullable<int> BORIENT3 { get; set; }
        public Nullable<int> BORIENT4 { get; set; }
        public Nullable<int> BORIENT5 { get; set; }
        public Nullable<int> BPAGE1 { get; set; }
        public Nullable<int> BPAGE2 { get; set; }
        public Nullable<int> BPAGE3 { get; set; }
        public Nullable<int> BPAGE4 { get; set; }
        public Nullable<int> BPAGE5 { get; set; }
        public Nullable<int> BCOLOR { get; set; }
        public Nullable<int> BNCOLOR { get; set; }
        public Nullable<int> BNSIZE { get; set; }
        public Nullable<int> BSTYLE { get; set; }
        public Nullable<int> BNSTYLE { get; set; }
        public string BFONT { get; set; }
        public string BNFONT { get; set; }
        public Nullable<int> BNHEIGHT { get; set; }
        public Nullable<int> GAPTIME { get; set; }
        public Nullable<int> DEMOCOUNT { get; set; }
        public Nullable<int> D9 { get; set; }
        public Nullable<int> D18 { get; set; }
        public Nullable<int> AUTODELETE { get; set; }
        public Nullable<int> AUTODAYS { get; set; }
        public Nullable<int> CERTNO { get; set; }
        public Nullable<int> TIEBREAK { get; set; }
        public Nullable<int> WHICHCAP { get; set; }
        public Nullable<int> ROUNDROB { get; set; }
        public Nullable<int> MATCHPLAY { get; set; }
        public Nullable<int> QUOTABASE { get; set; }
        public Nullable<int> KEEP_LAST { get; set; }
        public Nullable<int> HI_THROW { get; set; }
        public Nullable<int> LO_THROW { get; set; }
        public Nullable<int> QUAD_B { get; set; }
        public Nullable<int> TRIP_B { get; set; }
        public Nullable<int> DBL_B { get; set; }
        public Nullable<int> BOGIE { get; set; }
        public Nullable<int> PAR { get; set; }
        public Nullable<int> BIRDIE { get; set; }
        public Nullable<int> EAGLE { get; set; }
        public Nullable<int> D_EAGLE { get; set; }
        public Nullable<int> FORCE_LNF { get; set; }
        public string PROXY_URL { get; set; }
        public string PROXY_PORT { get; set; }
        public string PROXY_USERID { get; set; }
        public string PROXY_PWORD { get; set; }
        public Nullable<int> PROXY_USE { get; set; }
        public Nullable<System.DateTime> TIME_CONNECTED_SERV { get; set; }
        public Nullable<System.DateTime> TIME_CONNECTED_COMP { get; set; }
        public Nullable<System.DateTime> LAST_RUN_TIME_COMP { get; set; }
        public Nullable<int> RUN_COUNT_UNCONNECTED { get; set; }
        public Nullable<int> LAST_ANNUALFEE { get; set; }
        public Nullable<int> LAST_WEEKFEE { get; set; }
        public Nullable<int> SPONSOR_IDX { get; set; }
        public string R1TEXT { get; set; }
        public string R2TEXT { get; set; }
        public string R3TEXT { get; set; }
        public string R4TEXT { get; set; }
        public string R5TEXT { get; set; }
        public string R6TEXT { get; set; }
        public Nullable<int> TEECOLOR { get; set; }
        public Nullable<int> LBP1COLOR { get; set; }
        public Nullable<int> LBP2COLOR { get; set; }
        public Nullable<int> LBFONT1COLOR { get; set; }
        public Nullable<int> LBFONT2COLOR { get; set; }
        public Nullable<int> LBFONTSIZE { get; set; }
        public Nullable<int> LBFONTSTYLE { get; set; }
        public string LBFONTNAME { get; set; }
        public Nullable<int> LBIPAUSE { get; set; }
        public Nullable<int> LBSSPEEDM { get; set; }
        public Nullable<int> LBSSPEED { get; set; }
        public string REPORTDIR { get; set; }
        public string LBOARDDIR { get; set; }
    }
}
