//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMOVED
    {
        public string FACID { get; set; }
        public System.DateTime PLYFLD { get; set; }
        public int PLYFLDNO { get; set; }
        public int TOURN_NO { get; set; }
        public int PLYERID { get; set; }
    }
}
