//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCORE
    {
        public string FACID { get; set; }
        public System.DateTime PLYFLD { get; set; }
        public int PLYFLDNO { get; set; }
        public int RNDNO { get; set; }
        public int PLYERID { get; set; }
        public Nullable<double> CAPDEX { get; set; }
        public Nullable<int> HDCP { get; set; }
        public int NET { get; set; }
        public string THE_FLIGHT { get; set; }
        public Nullable<int> T0_CP { get; set; }
        public Nullable<int> T1_CP { get; set; }
        public Nullable<int> T2_CP { get; set; }
        public Nullable<int> T3_CP { get; set; }
        public Nullable<int> T4_CP { get; set; }
        public Nullable<int> T5_CP { get; set; }
        public Nullable<int> T6_CP { get; set; }
        public Nullable<int> T7_CP { get; set; }
        public Nullable<int> T8_CP { get; set; }
        public int T0_TM { get; set; }
        public Nullable<int> T1_TM { get; set; }
        public Nullable<int> T2_TM { get; set; }
        public Nullable<int> T3_TM { get; set; }
        public Nullable<int> T4_TM { get; set; }
        public Nullable<int> T5_TM { get; set; }
        public Nullable<int> T6_TM { get; set; }
        public Nullable<int> T7_TM { get; set; }
        public Nullable<int> T8_TM { get; set; }
        public Nullable<int> SK_R1 { get; set; }
        public Nullable<int> SK_N1 { get; set; }
        public Nullable<int> SK_R2 { get; set; }
        public Nullable<int> SK_R3 { get; set; }
        public Nullable<int> SK_R4 { get; set; }
        public Nullable<int> SK_R5 { get; set; }
        public Nullable<int> H_1 { get; set; }
        public Nullable<int> H_2 { get; set; }
        public Nullable<int> H_3 { get; set; }
        public Nullable<int> H_4 { get; set; }
        public Nullable<int> H_5 { get; set; }
        public Nullable<int> H_6 { get; set; }
        public Nullable<int> H_7 { get; set; }
        public Nullable<int> H_8 { get; set; }
        public Nullable<int> H_9 { get; set; }
        public Nullable<int> H_10 { get; set; }
        public Nullable<int> H_11 { get; set; }
        public Nullable<int> H_12 { get; set; }
        public Nullable<int> H_13 { get; set; }
        public Nullable<int> H_14 { get; set; }
        public Nullable<int> H_15 { get; set; }
        public Nullable<int> H_16 { get; set; }
        public Nullable<int> H_17 { get; set; }
        public Nullable<int> H_18 { get; set; }
        public Nullable<int> H_IN { get; set; }
        public Nullable<int> H_OUT { get; set; }
        public Nullable<int> H_TOT { get; set; }
        public Nullable<int> H_IN_6 { get; set; }
        public Nullable<int> H_IN_3 { get; set; }
        public Nullable<int> H_OUT_6 { get; set; }
        public Nullable<int> H_OUT_3 { get; set; }
        public Nullable<int> ADJ_SCORE { get; set; }
        public Nullable<int> C0TOT { get; set; }
        public Nullable<int> C1TOT { get; set; }
        public Nullable<int> C2TOT { get; set; }
        public Nullable<int> C3TOT { get; set; }
        public Nullable<int> C4TOT { get; set; }
        public Nullable<int> C5TOT { get; set; }
        public Nullable<int> C6TOT { get; set; }
        public Nullable<int> C7TOT { get; set; }
        public Nullable<int> C8TOT { get; set; }
        public Nullable<int> CH_TOT { get; set; }
        public Nullable<int> TEEORDER { get; set; }
        public Nullable<int> ORGORDER { get; set; }
        public Nullable<int> FLIGHT { get; set; }
        public Nullable<int> CX0 { get; set; }
        public Nullable<int> CX1 { get; set; }
        public Nullable<int> CX2 { get; set; }
        public Nullable<int> CX3 { get; set; }
        public Nullable<int> CX4 { get; set; }
        public Nullable<int> CX5 { get; set; }
        public Nullable<int> CX6 { get; set; }
        public Nullable<int> CX7 { get; set; }
        public Nullable<int> CX8 { get; set; }
        public Nullable<int> DUMMY { get; set; }
        public string ZNAME { get; set; }
        public Nullable<int> FX0 { get; set; }
        public Nullable<int> FX1 { get; set; }
        public Nullable<int> FX2 { get; set; }
        public Nullable<int> FX3 { get; set; }
        public Nullable<int> FX4 { get; set; }
        public Nullable<int> FX5 { get; set; }
        public Nullable<int> FX6 { get; set; }
        public Nullable<int> FX7 { get; set; }
        public Nullable<int> FX8 { get; set; }
        public Nullable<int> BX0 { get; set; }
        public Nullable<int> BX1 { get; set; }
        public Nullable<int> BX2 { get; set; }
        public Nullable<int> BX3 { get; set; }
        public Nullable<int> BX4 { get; set; }
        public Nullable<int> BX5 { get; set; }
        public Nullable<int> BX6 { get; set; }
        public Nullable<int> BX7 { get; set; }
        public Nullable<int> BX8 { get; set; }
        public Nullable<int> WALKER { get; set; }
        public Nullable<int> COURSE_GRP { get; set; }
        public Nullable<int> JUNK { get; set; }
        public Nullable<int> RPTHRU { get; set; }
        public Nullable<int> RP_TOT { get; set; }
        public Nullable<int> RP0TOT { get; set; }
        public Nullable<int> RP1TOT { get; set; }
        public Nullable<int> RP2TOT { get; set; }
        public Nullable<int> RP3TOT { get; set; }
        public Nullable<int> RP4TOT { get; set; }
        public Nullable<int> RP5TOT { get; set; }
        public Nullable<int> RP6TOT { get; set; }
        public Nullable<int> RP7TOT { get; set; }
        public Nullable<int> RP8TOT { get; set; }
        public Nullable<int> RPX0 { get; set; }
        public Nullable<int> RPX1 { get; set; }
        public Nullable<int> RPX2 { get; set; }
        public Nullable<int> RPX3 { get; set; }
        public Nullable<int> RPX4 { get; set; }
        public Nullable<int> RPX5 { get; set; }
        public Nullable<int> RPX6 { get; set; }
        public Nullable<int> RPX7 { get; set; }
        public Nullable<int> RPX8 { get; set; }
        public Nullable<int> RP_FX0 { get; set; }
        public Nullable<int> RP_FX1 { get; set; }
        public Nullable<int> RP_FX2 { get; set; }
        public Nullable<int> RP_FX3 { get; set; }
        public Nullable<int> RP_FX4 { get; set; }
        public Nullable<int> RP_FX5 { get; set; }
        public Nullable<int> RP_FX6 { get; set; }
        public Nullable<int> RP_FX7 { get; set; }
        public Nullable<int> RP_FX8 { get; set; }
        public Nullable<int> RP_BX0 { get; set; }
        public Nullable<int> RP_BX1 { get; set; }
        public Nullable<int> RP_BX2 { get; set; }
        public Nullable<int> RP_BX3 { get; set; }
        public Nullable<int> RP_BX4 { get; set; }
        public Nullable<int> RP_BX5 { get; set; }
        public Nullable<int> RP_BX6 { get; set; }
        public Nullable<int> RP_BX7 { get; set; }
        public Nullable<int> RP_BX8 { get; set; }
        public Nullable<int> RP_OUT { get; set; }
        public Nullable<int> RP_OUT_3 { get; set; }
        public Nullable<int> RP_OUT_6 { get; set; }
        public Nullable<int> RP_IN { get; set; }
        public Nullable<int> RP_IN_3 { get; set; }
        public Nullable<int> RP_IN_6 { get; set; }
        public string T0_CALOWNER { get; set; }
        public Nullable<int> T0_CALPRICE { get; set; }
        public string T1_CALOWNER { get; set; }
        public Nullable<int> T1_CALPRICE { get; set; }
        public string T2_CALOWNER { get; set; }
        public Nullable<int> T2_CALPRICE { get; set; }
        public string T3_CALOWNER { get; set; }
        public Nullable<int> T3_CALPRICE { get; set; }
        public string T4_CALOWNER { get; set; }
        public Nullable<int> T4_CALPRICE { get; set; }
        public string T5_CALOWNER { get; set; }
        public Nullable<int> T5_CALPRICE { get; set; }
        public string T6_CALOWNER { get; set; }
        public Nullable<int> T6_CALPRICE { get; set; }
        public string T7_CALOWNER { get; set; }
        public Nullable<int> T7_CALPRICE { get; set; }
        public string T8_CALOWNER { get; set; }
        public Nullable<int> T8_CALPRICE { get; set; }
        public Nullable<int> FEMALE { get; set; }
        public Nullable<int> MATCHORD { get; set; }
        public Nullable<int> T0_MT { get; set; }
        public Nullable<double> XINDEX { get; set; }
    }
}
