//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGLF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEETIME
    {
        public string FACID { get; set; }
        public System.DateTime PLYFLD { get; set; }
        public int PLYFLDNO { get; set; }
        public int RNDNO { get; set; }
        public Nullable<int> COURSE { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> STARTTIME2 { get; set; }
        public Nullable<System.DateTime> STARTTIME3 { get; set; }
        public Nullable<System.DateTime> STARTTIME4 { get; set; }
        public Nullable<int> GAPMINUTES { get; set; }
        public Nullable<int> GAP2 { get; set; }
        public Nullable<int> GAP3 { get; set; }
        public Nullable<int> GAP4 { get; set; }
        public Nullable<int> STARTHOLE { get; set; }
        public Nullable<int> STARTHOLE2 { get; set; }
        public Nullable<int> STARTHOLE3 { get; set; }
        public Nullable<int> STARTHOLE4 { get; set; }
        public Nullable<int> STARTGROUP { get; set; }
        public Nullable<int> DIRECTION { get; set; }
        public Nullable<int> SHOTGUN { get; set; }
        public Nullable<int> TWOTIMES { get; set; }
        public Nullable<int> THREETIMES { get; set; }
        public Nullable<int> FOURTIMES { get; set; }
        public Nullable<int> ONECOUNT { get; set; }
        public Nullable<int> TWOCOUNT { get; set; }
        public Nullable<int> THREECNT { get; set; }
        public Nullable<int> XSOME { get; set; }
        public Nullable<int> PPCART { get; set; }
        public Nullable<int> PPTEAM { get; set; }
        public Nullable<int> HOLE1 { get; set; }
        public Nullable<int> HOLE2 { get; set; }
        public Nullable<int> HOLE3 { get; set; }
        public Nullable<int> HOLE4 { get; set; }
        public Nullable<int> HOLE5 { get; set; }
        public Nullable<int> HOLE6 { get; set; }
        public Nullable<int> HOLE7 { get; set; }
        public Nullable<int> HOLE8 { get; set; }
        public Nullable<int> HOLE9 { get; set; }
        public Nullable<int> HOLE10 { get; set; }
        public Nullable<int> HOLE11 { get; set; }
        public Nullable<int> HOLE12 { get; set; }
        public Nullable<int> HOLE13 { get; set; }
        public Nullable<int> HOLE14 { get; set; }
        public Nullable<int> HOLE15 { get; set; }
        public Nullable<int> HOLE16 { get; set; }
        public Nullable<int> HOLE17 { get; set; }
        public Nullable<int> HOLE18 { get; set; }
    }
}
